export const TEST_ACTION = "TEST_ACTION";

// WORD INFO ACTIONS
export const GET_WORDINFO = "GET_WORDINFO";
export const GET_DEFINITION = "GET_DEFINITION";
export const WORDINFO_LOADING = "WORDINFO_LOADING";
